/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    InputNumber: typeof import('./src/components/InputNumber/InputNumber.vue')['default']
    InputText: typeof import('./src/components/InputText/InputText.vue')['default']
  }
}
