/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CustomInput: typeof import('./src/components/CustomInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber/InputNumber.vue')['default']
    InputText: typeof import('./src/components/InputText/InputText.vue')['default']
    Wrapper: typeof import('./src/components/Wrapper.vue')['default']
  }
}
